{
 "title": "Book  Rating",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Daily Active User (DAU)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\nto_char(count(DISTINCT (user_id)), '999,999,999')\n   AS DAU \nFROM rating \nWHERE\n  $__timeFilter(logtime);\n"
    }
   ]
  },
  {
   "title": "Top10 Hottest Books",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  b.title as book,\n  b.authors as author,\n  a.rating as rating,\n  a.avg_rate\nFROM\n  (SELECT\n     book_id,\n     count(rating) AS rating,\n     avg(rating::float) as avg_rate\n   FROM rating\n   where $__timeFilter(logtime) \n   GROUP BY 1\n   ORDER BY 2 DESC\n   LIMIT 10) AS a LEFT JOIN books AS b ON a.book_id = b.book_id ORDER BY rating DESC;\n\n"
    }
   ]
  },
  {
   "title": "Rating Total",
   "type": "singlestat",
   "description": "Total rating number",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(count(rating), '999,999,999')\n   AS rating_5_coun\nFROM rating \nWHERE\n  $__timeFilter(logtime);\n"
    }
   ]
  },
  {
   "title": "Rating distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n   getdate() as time, count(*) as star_5\nFROM rating\nwhere $__timeFilter(logtime) and rating = 5;"
    },
    {
     "rawSql": "SELECT\n   getdate() as time, count(*) as star_4\nFROM rating\nwhere $__timeFilter(logtime) and rating = 4;"
    },
    {
     "rawSql": "SELECT\n   getdate() as time, count(*) as star_3\nFROM rating\nwhere $__timeFilter(logtime) and rating = 3;"
    },
    {
     "rawSql": "SELECT\n   getdate() as time, count(*) as star_2\nFROM rating\nwhere $__timeFilter(logtime) and rating = 2;"
    },
    {
     "rawSql": "SELECT\n   getdate() as time, count(*) as star_1\nFROM rating\nwhere $__timeFilter(logtime) and rating = 1;"
    }
   ]
  },
  {
   "title": "User Rating",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(logtime) AS \"time\",\n  count(rating) as Rating\nFROM rating\nWHERE \n  $__timeFilter(logtime)\n  group by 1\n  order by 1 asc;\n"
    },
    {
     "rawSql": "SELECT\n  distinct(logtime) AS \"time\",\n  count(distinct(user_id)) as DAU\nFROM rating\nWHERE \n  $__timeFilter(logtime)\n  group by 1\n  order by 1 asc;"
    }
   ]
  }
 ]
}